### ISSUE TITLE
Issue with Debugging 

### ISSUE THREAD

**Issue by coastalfox** [managedcoder/TeamsEngagementHub#2]
Hi,

I am at the debugging stage and I am getting the following error

![Screenshot 2023-11-16 124942](https://github.com/managedcoder/TeamsEngagementHub/assets/150983261/91178daf-bd3f-40a3-be0d-62a27583746b)

Could you provide any advice on how to fix this?

Thank you

**Comment by managedcoder** [comment]
What step are you on from the README.md page?

**Comment by coastalfox** [comment]
Hello, 

I am on the below step.

Open \TeamsEngagementHub\EngagementHub\EngagementHub.csproj in Visual Studio and start the debugger (F5). This will run the backend APIs locally and the config files have been hardcoded to point to this running instance of the APIs

Thank you

**Comment by managedcoder** [comment]
I think you may have somehow opened something other than EngagementHub.csproj.  That error happens when the currently selected project in VS is not a runnable project, like a library project for example.  If you double click on the EngagementHub.csproj file it should open VS and point to the right project for step 11 and it should look like this: 
<img width="272" alt="image" src="https://github.com/managedcoder/TeamsEngagementHub/assets/17769186/560565b7-cb4d-4f01-b588-7a26520890f2">
Can you double click the project file and then hit F5 and let me know if it looks like what I've shown above and it that fixes your issue.

**Comment by managedcoder** [comment]
@coastalfox , where you able to try the suggestion I made?  Are you past this now?

**Comment by managedcoder** [comment]
I am going to close this issue and assume that my suggestion either fixed the problem or I did not get back to you fast enough and you have abandoned your exploration of this solution.  If you'd like to reopen this issue, just let me know.
